In [2]:

import mord
from mord.datasets.base import load_housing
from sklearn import linear_model, metrics, preprocessing

c:\python35\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.datasets.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)


In [10]:
 
import mord
import pandas as pd
import numpy as np
from sklearn import linear_model, metrics, preprocessing

In [30]:


# data_all = pd.read_csv(r'C:\Python35\Lib\site-packages\mord\datasets\data\copenhagen_housing_survey.csv')
# features_names = ('Infl', 'Type', 'Cont')
# target=data_all.loc[:,'Sat']
# features=data_all.loc[:,features]
# # print(data, target)
 

In [32]:
#https://stats.stackexchange.com/questions/108834/calculate-coefficients-in-a-ordinal-logistic-regression-with-r
import pandas as pd
import numpy as np
X = pd.read_csv("C:\\Users\\enisbe\\Documents\\jupyter\\data\\X.csv")
y = pd.read_csv("C:\\Users\\enisbe\\Documents\\jupyter\\data\\y.csv")
start = pd.read_csv("C:\\Users\\enisbe\\Documents\\jupyter\\data\\start.csv")
X = X.iloc[:,1:].to_numpy()
y  = np.ravel(  y.iloc[:,1:].to_numpy())
# s0 =start.iloc[:,1:].to_numpy()
np.set_printoptions(precision=4)
X  = X[:,[0,2]]

In [33]:
clf1 = linear_model.LogisticRegression(
    solver='lbfgs',
    multi_class='multinomial')
clf1.fit(X, y)

print('Mean Absolute Error of LogisticRegression: %s' %
      metrics.mean_absolute_error(clf1.predict(X), y))

clf2 = mord.LogisticAT(alpha=1.)
clf2.fit(X, y)
print('Mean Absolute Error of LogisticAT %s' %
      metrics.mean_absolute_error(clf2.predict(X), y))

clf3 = mord.LogisticIT(alpha=1.)
clf3.fit(X, y)
print('Mean Absolute Error of LogisticIT %s' %
      metrics.mean_absolute_error(clf3.predict(X), y))

clf4 = mord.LogisticSE(alpha=1.)
clf4.fit(X, y)
print('Mean Absolute Error of LogisticSE %s' %
      metrics.mean_absolute_error(clf4.predict(X), y))
 

Mean Absolute Error of LogisticRegression: 0.3970223325062035
Mean Absolute Error of LogisticAT 0.391232423490488
Mean Absolute Error of LogisticIT 0.3970223325062035
Mean Absolute Error of LogisticSE 0.39950372208436724


In [44]:
np.unique(y)

array([1, 2, 3, 4], dtype=int64)

In [45]:
# print(clf1.coef_)
# print(clf2.classes_)
# print(clf2.coef_)

print(clf2.coef_)
print(clf2.theta_)
# print(clf1.intercept_)
 
print(clf3.theta_)


[2.3443 0.8253]
[1.2445 3.217  4.0009]
[1.3836 2.1063 2.1063]
